### ISSUE TITLE
ens-log.txt not created if missing

### ISSUE THREAD

**Issue by mjmau** [ethers-io/ethers-ens#1]
When you first install and try to run `ethers-ens watch xyz.eth`, it raises an error because it cannot find ens-log.txt.

```
$ ethers-ens watch xyz.eth
Network: mainnet
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'ens-log.txt'
    at Object.fs.openSync (fs.js:584:18)
```

Workaround:
  `$ touch ens-log.txt`

**Comment by ricmoo** [comment]
Thanks! I will get this fix added shortly.

**Comment by ricmoo** [comment]
Thanks again.

Fixed, submitted and published on npm.
