### ISSUE TITLE
unable to reveal bid after deadline

### ISSUE THREAD

**Issue by mjmau** [ethers-io/ethers-ens#12]
If you forget to reveal a bid during the 48-hour reveal phase, and then try to reveal it, ethers-ens prints an error:
```
  Error: name already owned
```
However, it is still worthwhile to reveal the bid, as 0.5% of the bid can be claimed.

**Comment by ricmoo** [comment]
You are absolutely correct. I will add a `--force` flag today that will disable certain checks that make sense in edge cases.

For example, you may also wish to bid before an auction is started.

**Comment by ricmoo** [comment]
Updated. Please re-install ethers-ens via:

```
/Users/ethers> npm install -g ethers-ens
```

You should be able to reveal the bid of an expired auction to reclaim your 0.5%.
