### ISSUE TITLE
allow user to change the gas price

### ISSUE THREAD

**Issue by jadster** [ethers-io/ethers-ens#13]
I'd be great if I could change the gas price (e.g. when using --cheap) via some cli commands. Seems like things are working these days with 1Gwei or even less (with some patience)...

**Comment by ricmoo** [comment]
Ah yes, I need to remove `--cheap`. You can simply use `--gas-price GWEI` instead:

```javascript
// 1 Gwei
ethers-ens --gas-price 1 ...
// 0.1 Gwei
ethers-ens --gas-price 0.1 ...
```

**Comment by jadster** [comment]
olala olala very nice. thanks.

**Comment by ricmoo** [comment]
Just catching up on old issues. This is now (and has been for a while ;)) supported. :)
