### ISSUE TITLE
Import Bids

### ISSUE THREAD

**Issue by x011** [ethers-io/ethers-ens#14]
Hi there,
I've exported my bids from https://registrar.ens.domains, but when I try to import them with:

`ethers-ens import-bid /full/path/ens-bids-backup_2018-01-26T02_22_50.705Z.json`

I get an error:
```
Network: mainnet
{ [Error: invalid hexlify value] name: undefined, input: undefined }
```

Any idea why this is happening?

**Comment by ricmoo** [comment]
Can you look at the file in `node_modules/ethers-providers/package.json` and see what version of that package it is using? This bug was fixed in ethers.js a while ago, but maybe the `^2.1.0` semver isn't high enough to grab it. I will increase the version in the ethers-ens package.json anyways.

The other possibility is that the JSON file you have is slightly different than the tool is expecting. Can you send a copy to support@ethers.io. Please redact any fields you would like to keep private by replacing the values with the string "REDACTED". :)

**Comment by x011** [comment]
I managed to convert registrar.ens.domains json bids format to MEW  format, which seem to be supported by ethers-ens and was imported successfully.
The problem now is that when I try to `bid `or `reveal-bid` I get  only:

`Network: mainnet`

no password prompt or information like `Label Hash`, `Salt`, etc.


Example command:
`ethers-ens --account /full_path/to/wallet.json reveal-bid somename.eth 0.011`

any idea why?

Source for converting from **https://registrar.ens.domains**  to **MEW** https://medium.com/@nhirsch/importing-a-bid-created-in-mew-into-ens-and-vice-versa-60b31a174e98

**Comment by ricmoo** [comment]
Does it show up when you do a `ethers-ens scan-log`?

**Comment by x011** [comment]
No it doesn't, it simply exits the command and nothing is logged.
I've just tried:

`ethers-ens --account wallet.json bid somename.eth 0.01`
I'm prompted for a password but nothing happens after that.

**Comment by ricmoo** [comment]
If it did not ask for your password, it did not place a bid. Let me try this out on testnet.

**Comment by x011** [comment]
> "_**If it did not ask for your password, it did not place a bid**_"
It **did** ask for a password on `ethers-ens --account wallet.json bid somename.eth 0.01` but nothing happened or got logged after that.

**Comment by ricmoo** [comment]
This may be a result of https://github.com/ethers-io/ethers.js/issues/104.

I will fix that in the upstream dependency and then update this package to use the latest ethers.js.

**Comment by x011** [comment]
Ok, thank you. How should I proceed to update on my side?

**Comment by ricmoo** [comment]
I am updating [ethers.js](https://github.com/ethers-io/ethers.js) right now (the test cases are about 20% complete on my local copy). Once I commit, it will take about 30 minutes for Travis CI to complete the test suite, then I will update it and push the updates (after testing) to ethers-ens.

So, in about an hour, you can re-install ethers-ens. If you want it done sooner than later, you can also try using one of the other online tools like MEW or the ens.domains.

**Comment by x011** [comment]
Another issue importing bids, in this case made via MEW and imported on `ethers-dns`, is that they're all 
marked on `scan-log` as:

> Warning: placeBid(somename.eth, 0.01) is missing on the blockchain

Is this related to the fact that all bids placed on `MEW ` require the `--extra` parameter to hide the bid and `ether-ens ` cannot find the transactions?

**Comment by ricmoo** [comment]
That makes sense, I think. It means it saw you call "bid", but that your bid is not present on the blockchain. The call to the contract failed to reach the network. Once you have the latest version and place the bid again, that should go away.

**Comment by ricmoo** [comment]
This should be fixed now.

Please try:

```
/Users/ethers> npm install -g ethers-ens
```

And let me know if there are any more issues.

**Comment by x011** [comment]
I **confirm** that I'm able to place  bids with the new update. I'll have to wait for the next reveal in order to test the `reveal-bid` function.
Thank you vert much.

**Comment by ricmoo** [comment]
Awesome! Glad to hear it. :)
