### ISSUE TITLE
startAuctionsAndBid - Feature?

### ISSUE THREAD

**Issue by x011** [ethers-io/ethers-ens#15]
It seems that registrar.ens.domains uses `startAuctionsAndBid` function instead of `start-auction ` and `bid`.
Implementing the `startAuctionsAndBid` would save eth and time, do you plan to implement this?

**Comment by ricmoo** [comment]
I had not planned to support this, as it leaks information and connects a bidder to an auction.

This will also go away anyways, once we move to the rolling auction method.

I am open to a discussion on using it though. I think the gas difference is fairly small, but may be useful for tools that wish to use one transaction to place a bid, but there would need to be some documentation explaining the privacy issues.

**Comment by x011** [comment]
I guess you could create a `--no_privacy` override switch and allow users to start an auction and bid at once by using `startAuctionsAndBid`

**Comment by ricmoo** [comment]
Sorry catching up on old issues...

This is no longer relevant since the legacy auction is no longer used... So, closing. :)
