### ISSUE TITLE
Gwei Price 99 - Auto Gwei?

### ISSUE THREAD

**Issue by x011** [ethers-io/ethers-ens#16]
Since the last night update, [Gwei is set to 99](https://etherscan.io/tx/0x00045b8562b64ba33a54814692b05da0e184c87fde72bd829a2ece46bc89ebc9) by default, this is way to much, specially when the gas price was only **1 Gwei** at that time.
I've just paid **$9.37** for  a reveal bid execution - https://www.dropbox.com/s/oc9jr9n7gvzps4y/ss_144.jpg?dl=0
It would be nice to grab the [gas price](https://ethgasstation.info/ ) before every transaction. this would create a small delay in execution but we'd always pay the lowest price.

I'm aware that we can use `--gas-price` or `--cheap`  in order to set a lower gas price, but way too often I forget to set it and, as explained above, it can be costly.
Having the gas price set by default to the lowest price would prevent situations like this one.

**Comment by ricmoo** [comment]
I think this must have been during the ICO-wars. :)

The `provider.getGasPrice()` should be more sane now, but please let me know (in the [new repository](https://github.com/ethers-io/ethers.js)) if you still have problems. :)
