### ISSUE TITLE
Subnode Creation

### ISSUE THREAD

**Issue by x011** [ethers-io/ethers-ens#17]
Hi there,
How can we create a new `set-subnode` like **sub.myname.eth**?
Is there any particular command sequence that we should follow?
Thank  you!

**Comment by ricmoo** [comment]
Sorry catching up on old issues...

This is available using `ethers-ens --account wallet.json set-subnode sub.myname.eth`. The account must be the "controller" of `myname.eth`, but otherwise it should be all good.

Thanks! :)
