### ISSUE TITLE
Release ENS names

### ISSUE THREAD

**Issue by jadster** [ethers-io/ethers-ens#18]
Any plans to add functionality for releasing names (releaseDeed)?

**Comment by ricmoo** [comment]
Oh! Great idea. Yes. :)

I plan to update the underlying library to use ethers.js v4 this week once I release it, but releaseDeed should be ported to the legacy version too. A year ago it didn’t seem very important and had no meaningful way to be tested...

I’ll get to it this week. :)

**Comment by jadster** [comment]
superb! thanks.

Why would anyone want to use the legacy version going forward?

**Comment by ricmoo** [comment]
There may be people who are using the v3 library, and since the v4 library is not backwards compatible, I want to make sure I don't break them.

So, the ethers-ens library will receive a major version bump too, and will be much more compatible with the new Signer and Provider objects.

**Comment by ricmoo** [comment]
Catching up on old issues...

Is this still needed? It may be useful for anyone that hasn't migrated to the new registrar in the future. If anyone needs it, please open a new issue in the [new repository](https://github.com/ethers-io/ethers.js), but I'm cleaning this one up to archive it. :)
