### ISSUE TITLE
3-6 character auction

### ISSUE THREAD

**Issue by jadster** [ethers-io/ethers-ens#20]
Hola
Just wondering: Do you intend to support the upcoming 3-6 character auction with your tool as well?
https://medium.com/the-ethereum-name-service/announcing-the-ens-3-6-character-auction-31bfee7a4eab

**Comment by ricmoo** [comment]
Absolutely!

Basically anything ENS will be supported, and I chat regularly with the ENS team to keep up to date. :)

**Comment by jadster** [comment]
Yes! Good to know. thx & MC :-)

**Comment by ricmoo** [comment]
Sorry catching up on old issues...

The 3-6 letter auction has concluded (it was done on opensea) and 3-6 letter domains are now normally available using the 1-minute commit-reveal, the same as all other names now. :)

Thanks! :)
