### ISSUE TITLE
Feature Request: Should be able to reveal bids placed from MEW or the DAPP

### ISSUE THREAD

**Issue by DutchBoyd** [ethers-io/ethers-ens#5]
Have a few bids from MyEtherWallet that I'm trying to reveal. It looks like if the bid was not made using the command line tool, it can't be revealed either. Perhaps I'm just messing up the --salt field, or maybe it's looking through the log file or somewhere else.  

I tried a number of workarounds, like adding a placeBid entry in the ens-log.txt. This kind of worked, as the scan-log would then show the name and give warnings for names that haven't been revealed. But I still can't seem to reveal from the command line tool. 

I keep getting thrown an error like this:

`(node:6464) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): {name}.eth: bid not found`

---------------

Nice work by the way on this tool. It's definitely saving me a lot of headache from when I was placing bids through the dApp and then MEW.

**Comment by ricmoo** [comment]
Glad to hear you otherwise like the tool.

MEW *should* work, but I haven't tried it. I will try a bid on MEW today and see why it may not be working.

**Comment by ricmoo** [comment]
Done. See: https://github.com/ethers-io/ethers-ens/commit/fccead47e1fad190e1ad8c8402676348cca6feeb

```
/Users/ethers> ethers-ens import-bid FILENAME
```
