### ISSUE TITLE
Unsupported key-derivation function using Parity wallet

### ISSUE THREAD

**Issue by mjmau** [ethers-io/ethers-ens#6]
I tried to bid using a Parity JSON wallet file, but got an error:

`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: unsupported key-derivation function`

The JSON file is structured like this:
```
{
   "id" : "...",
   "name" : "...",
   "address" : "...",
   "crypto" : {
      "cipherparams" : {
         "iv" : "..."
      },
      "ciphertext" : "...",
      "mac" : "...",
      "kdf" : "pbkdf2",
      "kdfparams" : {
         "dklen" : 32,
         "c" : 10240,
         "prf" : "hmac-sha256",
         "salt" : "..."
      },
      "cipher" : "aes-128-ctr"
   },
   "meta" : "{}",
   "version" : 3
}
```

**Comment by ricmoo** [comment]
Ack! I didn't think anyone actually used the PBKDF2 "hardened" version of Version 3, since it isn't very future-proof.

I will add support for that tonight or tomorrow to [ethers.js](https://github.com/ethers-io/ethers.js), then `ethers-ens` will support it.

Here is the updated issue to track progress: https://github.com/ethers-io/ethers.js/issues/20

**Comment by mjmau** [comment]
I don't recall when Parity made this wallet for me, but I don't recall doing anything special. Should I try to "upgrade" my wallet?

**Comment by ricmoo** [comment]
Heya! This has been added upstream in ethers.js (https://github.com/ethers-io/ethers.js/commit/91f9a47afaf12626e07053da331a7e1974aee4c9):

Just re-install ethers-ens, and the latest version will be installed with PBKDF2 support.
```
sudo npm install -g ethers-ens
```

It looks like Parity still generates PBKDF2 wallets. I will ping Gavin to see if there is a reason. So, upgrading your wallet will likely not affect anything.
